### ISSUE TITLE
height = 100vh disables toc

### ISSUE THREAD

**Issue by kir12** [afeld/bootstrap-toc#31]
so i put a jumbotron above the rows to create like a title-header thing for my website. I set it to 100vh to get a nifty look where the first thing the user sees is the opener. But the thing is when I did, the toc gets disabled, i.e. it doesn't print on the screen. I think it might be because of the 100vh, but are there any possible workarounds?

*also it appears that the TOC is locked to the place where it's first rendered (at least using the default toc)

**Comment by afeld** [comment]
Have a link, or can you make a JSFiddle or something demonstrating the behavior?

> when I did, the toc gets disabled

Are you sure it's not there, just hidden?

> it appears that the TOC is locked to the place where it's first rendered

Right...see the mentions of "affix" in https://afeld.github.io/bootstrap-toc/#layout.

---

I'm going to close this issue since it doesn't seem like a bug, but happy to continue the conversation.
