### ISSUE TITLE
Support unicode CJK characters in headings

### ISSUE THREAD

**Issue by doowzs** [afeld/bootstrap-toc#49]
Hi, I use some Chinese characters in my headings, and I found that the auto generated ID of elements is like ``#-`` or ``#--1`` and some of them violate selector's grammar, making the script fail to run.

I tried to modify the code in the following way and it works, preserving main CJK characters in unicode.

Modify this line
```javascript
var anchor = text.trim().toLowerCase().replace(/[^A-Za-z0-9]+/g, '-');
```
to
```javascript
// https://stackoverflow.com/questions/21109011/javascript-unicode-string-chinese-character-but-no-punctuation
var anchor = text.trim().toLowerCase().replace(/[^A-Za-z0-9\u4E00-\u9FCC]+/g, '-');
```

**Comment by afeld** [comment]
Hey there, thanks for the issue! I haven't had to deal with Chinese characters in code before, so definitely missed that.

Rather than try to handle all different character sets, doing some research on the easiest way to solve it for all languages. If you (or anyone else) has ideas, would love to hear them!
